import type { SkillRule } from "./skillVisual.types";

/** Main skill node (세트) — stronger frames, slightly higher priorities on nuanced rules. */
export const SET_SKILL_RULES: SkillRule[] = [
  {
    keywords: ["환경", "분석", "리서치"],
    priority: 50,
    icon: "mdi:chart-areaspline",
    category: "analysis",
    theme: "cyan",
    bgStyle: "orb",
    glow: "medium",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["전략", "기획", "계획"],
    priority: 55,
    icon: "mdi:map",
    category: "strategy",
    theme: "purple",
    bgStyle: "rune",
    glow: "medium",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["고객", "발굴", "접근"],
    priority: 48,
    icon: "mdi:account-search",
    category: "relationship",
    theme: "blue",
    bgStyle: "plate",
    glow: "soft",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["상담", "커뮤니케이션", "관계"],
    priority: 52,
    icon: "mdi:forum",
    category: "relationship",
    theme: "green",
    bgStyle: "orb",
    glow: "soft",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["제안", "솔루션", "설계"],
    priority: 54,
    icon: "mdi:lightbulb-on",
    category: "strategy",
    theme: "orange",
    bgStyle: "plate",
    glow: "medium",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["협상", "조율"],
    priority: 53,
    icon: "mdi:handshake",
    category: "relationship",
    theme: "green",
    bgStyle: "rune",
    glow: "medium",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["계약", "체결", "약정"],
    priority: 56,
    icon: "mdi:file-sign",
    category: "execution",
    theme: "blue",
    bgStyle: "plate",
    glow: "strong",
    frame: "epic",
    filled: true,
  },
  {
    keywords: ["이행", "사후", "관리", "유지"],
    priority: 51,
    icon: "mdi:clipboard-check",
    category: "execution",
    theme: "cyan",
    bgStyle: "plate",
    glow: "soft",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["성과", "KPI", "목표"],
    priority: 57,
    icon: "mdi:target-variant",
    category: "performance",
    theme: "gold",
    bgStyle: "orb",
    glow: "strong",
    frame: "epic",
    filled: true,
  },
  {
    keywords: ["리스크", "이슈"],
    priority: 58,
    icon: "mdi:alert",
    category: "risk",
    theme: "red",
    bgStyle: "rune",
    glow: "strong",
    frame: "rare",
    filled: true,
  },
  {
    keywords: ["가격", "견적", "수익", "매출"],
    priority: 52,
    icon: "mdi:currency-krw",
    category: "finance",
    theme: "gold",
    bgStyle: "plate",
    glow: "medium",
    frame: "rare",
    filled: true,
  },
];

/** Smaller ability chips — common frames, tuned keywords from former ABILITY_RULES. */
export const ABILITY_SKILL_RULES: SkillRule[] = [
  {
    keywords: ["환경", "시장", "경쟁", "리서치", "분석", "조사"],
    priority: 50,
    icon: "mdi:chart-line",
    category: "analysis",
    theme: "cyan",
    bgStyle: "orb",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["전략", "기획", "계획", "로드맵"],
    priority: 52,
    icon: "mdi:map-marker-path",
    category: "strategy",
    theme: "purple",
    bgStyle: "rune",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["발굴", "리드", "잠재", "탐색"],
    priority: 48,
    icon: "mdi:account-search",
    category: "relationship",
    theme: "blue",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["접근", "미팅", "컨택"],
    priority: 47,
    icon: "mdi:account-arrow-right",
    category: "relationship",
    theme: "blue",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["상담", "커뮤니케이션", "관계", "응대"],
    priority: 51,
    icon: "mdi:forum",
    category: "relationship",
    theme: "green",
    bgStyle: "orb",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["니즈", "요구", "진단"],
    priority: 49,
    icon: "mdi:clipboard-search",
    category: "analysis",
    theme: "cyan",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["제안", "솔루션", "설계"],
    priority: 53,
    icon: "mdi:lightbulb-on",
    category: "strategy",
    theme: "orange",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["협상", "조율"],
    priority: 52,
    icon: "mdi:handshake",
    category: "relationship",
    theme: "green",
    bgStyle: "rune",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["계약", "체결", "약정"],
    priority: 54,
    icon: "mdi:file-sign",
    category: "execution",
    theme: "blue",
    bgStyle: "plate",
    glow: "medium",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["이행", "사후", "유지", "관리"],
    priority: 50,
    icon: "mdi:clipboard-check",
    category: "execution",
    theme: "cyan",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["고객", "서비스"],
    priority: 46,
    icon: "mdi:account-heart",
    category: "relationship",
    theme: "green",
    bgStyle: "orb",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["가격", "견적", "정산", "수익", "매출"],
    priority: 51,
    icon: "mdi:currency-krw",
    category: "finance",
    theme: "gold",
    bgStyle: "plate",
    glow: "soft",
    frame: "common",
    filled: true,
  },
  {
    keywords: ["지식", "O*NET", "학습"],
    priority: 49,
    icon: "mdi:book-open-variant",
    category: "learning",
    theme: "purple",
    bgStyle: "rune",
    glow: "soft",
    frame: "common",
    filled: true,
  },
];
